export const detailedSources = {
  fox: {
    title: "Invertebrate Anatomy OnLine: Periplaneta americana",
    author: "Richard Fox · Lander University · 2006",
    type: "大學解剖實驗教材",
    url: "https://lanwebs.lander.edu/faculty/rsfox/invertebrates/periplaneta.html",
    scope:
      "核對頭部、口器、胸足、腹板及背側解剖次序。教材有部分 P. fuliginosa 圖與一般蟑螂圖，僅採其共有構造，不將它們視為美洲蟑螂的個體測量。以較新的物種研究補充生理敘述。",
  },
  trachealCT: {
    title:
      "Comparative anatomy of the insect tracheal system, Part 1 · Periplaneta americana",
    author: "Herhold, Davis, DeGrey & Grimaldi · AMNH Bulletin 459 · 2023",
    type: "同儕審查研究 · 微型 CT",
    url: "https://zenodo.org/records/7733331",
    scope:
      "核對氣管在頭、胸、腹及足中的分支。作者指出此標本的掃描解析度為 38 μm，某些小分支不能辨識；本網站未導入或分割該 CT 資料，不宣稱重建全部微氣管。",
  },
  legCT: {
    title:
      "Comparative Morphology of the Extrinsic and Intrinsic Leg Musculature in Dictyoptera",
    author: "Journal of Morphology · 2024 · DOI: 10.1002/jmor.70013",
    type: "同儕審查研究 · 微型 CT",
    url: "https://pubmed.ncbi.nlm.nih.gov/39648403/",
    scope:
      "依公開摘要、圖說中的美洲蟑螂雌成蟲胸足肌肉重建核對肌群方向與位置。未下載作者的分割網格；本網站的肌束不是逐條對應研究中的所有肌肉。",
  },
  mandibleCT: {
    title:
      "Fast and Powerful: Biomechanics and Bite Forces of the Mandibles in the American Cockroach Periplaneta americana",
    author: "Weihmann et al. · PLOS ONE · 2015",
    type: "同儕審查研究 · 微型 CT",
    url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0141226",
    scope:
      "核對咀嚼式大顎、左右齒列的非對稱及開顎肌／閉顎肌與內骨突的關係。依公開全文與圖 1 讀取，不把示意肌束當成實測形狀。",
  },
  wingVeins: {
    title: "The wing-venation of the American cockroach Periplaneta americana",
    author:
      "John Smart · Proceedings of the Zoological Society of London · 1951",
    type: "同儕審查研究 · 公開摘要",
    url: "https://doi.org/10.1111/j.1096-3642.1951.tb00750.x",
    scope:
      "核對前、後翅脈序須分別處理，以及歷史脈名解讀存在差異。僅取得摘要，不據此宣稱每條渲染翅脈已精確定名；程式翅脈為受形態約束的近似。",
  },
  tarsalPads: {
    title:
      "A Temperature Receptor in the Tarsus of the Cockroach, Periplaneta americana",
    author: "Journal of Experimental Biology 34:486–500 · 1957",
    type: "同儕審查研究 · 公開摘要",
    url: "https://journals.biologists.com/jeb/article/34/4/486/13221/A-Temperature-Receptor-in-the-Tarsus-of-the",
    scope:
      "核對爪間中墊以及前四個跗小節的墊狀構造。此研究涉及溫度敏感區域，不用它推論所有附著機制。",
  },
};

const p = (
  id,
  name,
  en,
  system,
  location,
  description,
  detail,
  note,
  refs,
  options = {},
) => ({
  id,
  name,
  en,
  system,
  location,
  description,
  detail,
  note,
  refs,
  ...options,
});
export const detailedParts = [
  p(
    38,
    "頭殼與顏面",
    "Head capsule",
    "external",
    "前胸背板下方，口器朝腹側",
    "頭殼包覆腦、前段消化道與口器肌肉。",
    "以立體頭殼取代與背板合併的平面輪廓；額、頭楯與頰部以表面分區表達。頭部可部分縮入前胸下。",
    "切到腹面或局部觀察，可以看見背面視角被遮蔽的顏面。",
    ["fox", "mandibleCT"],
    { depth: 0 },
  ),
  p(
    39,
    "上唇",
    "Labrum",
    "external",
    "口前腔前側、頭楯末端",
    "上唇覆蓋口前腔的前緣。",
    "這片可活動的骨片位於大顎前方，與下唇共同界定口器周圍的空間。",
    "上唇、大顎與下唇是不同構造；局部觀察分別顯示。",
    ["fox"],
    { depth: 0 },
  ),
  p(
    40,
    "舌狀下咽",
    "Hypopharynx",
    "digestive",
    "口前腔內，唾液通道附近",
    "參與口前腔內食物與唾液的處理。",
    "這是頭部體壁形成的內突，並非一對分節附肢。模型將它放在大顎、上唇與下唇圍成的空間內。",
    "尺寸很小，需局部觀察；沒有重建感覺細胞或腺管上皮。",
    ["fox"],
    { depth: 0 },
  ),
  p(
    41,
    "基節",
    "Coxae",
    "external",
    "前、中、後胸腹外側，各一對",
    "寬大的基節把每隻足連接到胸部。",
    "六個基節各有胸節歸屬，並容納肌肉及氣管。牠們不是長在腹部的六個支點。",
    "局部觀察保留六個基節，方便比較前、中、後足。",
    ["fox", "legCT", "trachealCT"],
    { depth: 0 },
  ),
  p(
    42,
    "轉節",
    "Trochanters",
    "external",
    "基節與腿節之間",
    "短小的關節區連接基節與腿節。",
    "轉節與相鄰關節把胸部和足內肌肉產生的力量傳到長腿節。",
    "足的順序為基節、轉節、腿節、脛節、跗節。",
    ["fox", "legCT"],
    { depth: 0 },
  ),
  p(
    43,
    "腿節",
    "Femora",
    "external",
    "轉節遠端，較粗的長足節",
    "支承與運動所需的肌肉位於腿節內。",
    "腿節遠比跗小節粗，與脛節的鉸接位置清楚可見；腹側棘與細毛以獨立表面幾何表達。",
    "棘刺數與角度為近似；未聲稱符合每隻足的分類計數。",
    ["indoorAtlas", "legCT"],
    { depth: 0 },
  ),
  p(
    44,
    "脛節與脛棘",
    "Tibiae and tibial spines",
    "external",
    "腿節與跗節之間",
    "細長脛節帶有醒目的尖棘。",
    "模型使用收細的脛節、雙列較粗棘及較細表面毛，區分不同尺度的外部構造。",
    "切換腹面、側面可檢查棘的位置；棘不是額外足節。",
    ["indoorAtlas", "legCT"],
    { depth: 0 },
  ),
  p(
    45,
    "五節跗節",
    "Five tarsomeres",
    "external",
    "每隻足末端，爪的近端",
    "五個跗小節連續排列，使足端貼合表面。",
    "每隻足都有五個真正分開的跗小節，近端第一節較長；末端接爪與中墊。",
    "放大觀察比在全身畫面數小節更清楚。",
    ["fox", "tarsalPads"],
    { depth: 0 },
  ),
  p(
    46,
    "成對跗爪",
    "Pretarsal claws",
    "external",
    "跗節最末端，位於中墊兩側",
    "彎曲的硬爪可與粗糙表面接合。",
    "模型為每隻足建立一對彎爪，與軟墊分開標示。爪位於末端，並不是第六個跗小節。",
    "爪尖是三維彎曲構造；需以側面或局部觀察辨認。",
    ["fox", "tarsalPads"],
    { depth: 0 },
  ),
  p(
    47,
    "跗墊與爪間中墊",
    "Euplantulae and arolium",
    "external",
    "跗小節腹側及兩爪之間",
    "足端有軟墊狀接觸構造。",
    "前四個跗小節腹面及兩爪之間分別顯示墊狀區，材質比硬化足節柔和、偏淡色。",
    "模型表達位置，不模擬黏液、接觸力或微細表面紋理。",
    ["tarsalPads"],
    { depth: 0 },
  ),
  p(
    48,
    "腹部背板",
    "Abdominal terga",
    "external",
    "腹部背側，成蟲翅下方",
    "分節背板覆蓋腹部，節間膜允許變形。",
    "背板有曲率、薄邊與前後重疊；後方小背板與腹端板不同。",
    "模型將背板成組向兩側移開以露出內臟，這不是活體關節運動。",
    ["fox", "skeleton"],
    { depth: 2 },
  ),
  p(
    49,
    "三個胸節與胸板",
    "Thoracic segments and sclerites",
    "external",
    "頭部後方，腹部之前",
    "前、中、後胸承載六足；中、後胸分別承載前、後翅。",
    "胸部不只是一片背板，還有背、側、腹面的骨片與肌肉附著區。",
    "中、後胸背板隨解剖層移開；前胸背板可另選 22 號。",
    ["fox", "legCT"],
    { depth: 2 },
  ),
  p(
    50,
    "腹部腹板",
    "Abdominal sterna",
    "external",
    "腹部腹側",
    "腹板保護腹側體壁與神經系統。",
    "胸腹板不應與背板畫成相同的一張圖。模型腹面有獨立骨片，末端另外依性別顯示生殖下板。",
    "請切換腹面觀察；外部可見的腹板數受性別與重疊影響。",
    ["fox"],
    { depth: 0 },
  ),
  p(
    51,
    "柄節與觸角基部",
    "Scape and antennal base",
    "nervous",
    "頭部兩側的觸角插入處",
    "較粗的柄節支承細長觸角。",
    "觸角包含基部柄節、梗節與遠端鞭節；模型區分基部與多節、漸細的鞭部。",
    "鞭部分節密度為渲染近似，不能用畫面推算真實感覺器數目。",
    ["antenna", "trachealCT"],
    { depth: 0 },
  ),
  p(
    52,
    "下唇",
    "Labium",
    "external",
    "口前腔後側、腹面",
    "下唇構成口器的後方界面。",
    "下唇由融合的附肢形成，與成對小顎不同。模型顯示中央唇部與較短的下唇鬚。",
    "唇的細小內葉、外葉尚未逐片重建，不把表面輪廓當作完整分類圖。",
    ["fox"],
    { depth: 0 },
  ),
  p(
    53,
    "小顎鬚與下唇鬚",
    "Maxillary and labial palps",
    "nervous",
    "口器兩側",
    "口鬚協助感受與接觸食物。",
    "較長的小顎鬚有五節，較短的下唇鬚有三節；此處以分開的關節幾何呈現。",
    "可由腹面觀察兩組鬚；其尖端感覺毛只做有限度表達。",
    ["fox", "antenna"],
    { depth: 0 },
  ),
  p(
    54,
    "肛上板與腹端",
    "Supra-anal plate",
    "external",
    "腹部後端，肛門背側",
    "腹端背側的薄板覆蓋末端開口附近。",
    "美洲蟑螂肛上板末緣可見中央凹缺；兩側尾鬚是不同構造。",
    "左右形狀與凹缺深度為外形重建，不供物種鑑別測量。",
    ["indoorAtlas", "fox"],
    { depth: 0 },
  ),
  p(
    55,
    "翼狀肌與背隔膜",
    "Alary muscles and dorsal diaphragm",
    "circulatory",
    "背血管兩側，內臟背方",
    "薄的肌肉與隔膜參與背側血腔的支承。",
    "扇形肌束從體壁向背血管兩側延伸，位置在消化道上方。",
    "展示代表性肌束，未逐一標定每個心門與肌肉附著點。",
    ["blood", "fox"],
  ),
  p(
    56,
    "氣管螺旋內膜",
    "Tracheal taenidia",
    "respiratory",
    "較粗氣管的管壁",
    "螺旋狀表皮增厚有助維持氣管通暢。",
    "局部粗氣管有連續螺旋幾何，可用放大功能查看；氣管管腔不是血管。",
    "螺旋粗細經放大以便閱讀，不是依 38 μm CT 量測重建。",
    ["air", "trachealCT", "fox"],
  ),
  p(
    57,
    "前胃齒板",
    "Proventricular toothed plates",
    "digestive",
    "前胃內腔",
    "硬化齒板參與機械性研磨。",
    "六個主要齒列位於前胃內部。局部觀察會移除遮蔽的器官壁。",
    "細小刷毛、墊板與組織層未全部重建。",
    ["gizzard", "fox"],
  ),
  p(
    58,
    "直腸墊",
    "Rectal pads",
    "digestive",
    "直腸內壁，沿長軸排列",
    "直腸墊參與回收水分與溶質。",
    "六個延長墊狀構造圍繞內腔，與器官的長軸大致平行。",
    "直接選此部位可查看內部排列；組織學層次尚未分割。",
    ["rectum", "fox"],
  ),
  p(
    59,
    "卵巢管與卵母細胞",
    "Ovarioles and oocytes",
    "reproductive",
    "每側卵巢內，連向側輸卵管",
    "卵巢由卵巢管組成，卵母細胞沿管成熟。",
    "每側以八條卵巢管呈現，末端卵母細胞較大，往前逐漸變細。卵巢管末端匯入兩側的輸卵管。",
    "成熟狀態、大小與彎曲姿態會隨生殖週期而變。",
    ["female", "fox"],
    { sex: "female" },
  ),
  p(
    60,
    "大顎開閉肌",
    "Mandibular opener and closer muscles",
    "external",
    "頭殼內，連接大顎與內骨突",
    "較大的閉顎肌與較小的開顎肌驅動咀嚼。",
    "方向與相對大小參考美洲蟑螂微型 CT 與力學研究；以平行肌束連向下方的大顎。",
    "本模型沒有導入研究的原始分割，不能據此估算咬合力。",
    ["mandibleCT"],
  ),
  p(
    61,
    "咽部",
    "Pharynx",
    "digestive",
    "口腔之後、頭殼內",
    "咽部把口器處理過的食物送向食道。",
    "咽與食道屬連續通道，並穿過頭部神經系統形成的環繞區域。",
    "管徑與咽部肌肉目前為宏觀重建，未顯示黏膜或細胞。",
    ["fox", "gut"],
  ),
  p(
    62,
    "雄性腹刺",
    "Male styli",
    "reproductive",
    "雄性腹部第九腹板後緣",
    "雄成蟲有一對短小、不分節的腹刺。",
    "腹刺與較長、有分節且具感覺毛的尾鬚不同；雌成蟲不顯示此構造。",
    "選擇雄性並切到腹面，比背面更容易辨認。",
    ["ufsex", "fox"],
    { sex: "male", depth: 0 },
  ),
  p(
    63,
    "雌性生殖下板",
    "Female subgenital plate",
    "reproductive",
    "雌性腹部腹側末端",
    "第七腹板延伸的區域遮蔽生殖腔。",
    "雌性的末端腹面與雄性不同，不僅是把卵巢換成精巢。模型有成對的後方葉片。",
    "生殖腔中的三對產卵瓣及所有膜片尚未逐片重建。",
    ["fox"],
    { sex: "female", depth: 0 },
  ),
  p(
    64,
    "雄性生殖下板",
    "Male subgenital plate",
    "reproductive",
    "雄性腹部第九腹板",
    "覆蓋雄性腹端生殖區，後緣帶腹刺。",
    "雄性後方腹板較窄，與雌性擴大的第七腹板有可見差異。",
    "複雜的陽莖葉與分類用硬片尚未重建，不能作為外生殖器鑑定模型。",
    ["fox"],
    { sex: "male", depth: 0 },
  ),
];
