import { detailedParts, detailedSources } from "./anatomy-detail.js";
export const systems = [
  {
    id: "external",
    name: "外部構造",
    en: "EXTERNAL",
    color: "#98623c",
    icon: "scan",
  },
  {
    id: "digestive",
    name: "消化與排泄",
    en: "DIGESTION",
    color: "#bb784f",
    icon: "route",
  },
  {
    id: "respiratory",
    name: "呼吸系統",
    en: "RESPIRATION",
    color: "#4d8588",
    icon: "wind",
  },
  {
    id: "circulatory",
    name: "循環與代謝",
    en: "CIRCULATION",
    color: "#aa5c58",
    icon: "heart-pulse",
  },
  {
    id: "nervous",
    name: "神經與感官",
    en: "NERVOUS SYSTEM",
    color: "#a48840",
    icon: "activity",
  },
  {
    id: "reproductive",
    name: "生殖系統",
    en: "REPRODUCTION",
    color: "#8f7798",
    icon: "sprout",
  },
];

export const sources = {
  ...detailedSources,
  indoorAtlas: {
    title:
      "台灣常見室內節肢動物圖鑑：居家常見101種蟲蟲大集合，教你如何分辨與防治 · 美洲家蠊",
    author: "李鍾旻、詹美鈴 · 聯經出版 · 2021",
    label: "補充圖鑑 · 美洲家蠊（出版資訊）",
    type: "使用者提供的圖鑑節錄",
    url: "https://store.linkingbooks.com.tw/product/141181",
    scope:
      "依使用者提供的兩張截圖核對外觀：紅褐色具光澤的成蟲、前胸背板淡黃邊緣及近 T 形中央深色區、腎形複眼、細長觸角、具棘刺的足與尾鬚。第一張可見頁碼 49，第二張頁碼未顯示。連結供查閱出版資訊，並非節錄全文。斑紋有個體差異；若蟲照片不作為成蟲翅的依據。",
  },
  uf: {
    title: "American Cockroach, Periplaneta americana",
    author: "K. A. Barbara · University of Florida / IFAS",
    type: "大學昆蟲學資料",
    url: "https://ask.ifas.ufl.edu/publication/IN298",
    scope: "美洲蟑螂的外形、翅與生活史。",
  },
  ufsex: {
    title: "American cockroach · morphology and sex differences",
    author: "University of Florida / IFAS",
    type: "大學昆蟲學資料",
    url: "https://entnemdept.ufl.edu/projex/gallery/dl/cockroaches/text/american_cockroach.htm",
    scope: "尾鬚、雄性腹刺與雌雄差異。",
  },
  external: {
    title: "Order Blattodea",
    author: "NC State University · ENT 425",
    type: "大學教學資料",
    url: "https://genent.cals.ncsu.edu/insect-identification/order-blattodea/",
    scope: "長觸角、前胸背板、尾鬚等蟑螂辨識特徵。",
  },
  skeleton: {
    title: "Reasons for Success · Exoskeleton",
    author: "NC State University · ENT 425",
    type: "大學教學資料",
    url: "https://genent.cals.ncsu.edu/bug-bytes/success/",
    scope: "昆蟲表皮、幾丁質與肌肉附著的一般原理。",
  },
  lab: {
    title: "Morphology Part 2: Insect Internal Anatomy",
    author: "NC State University · ENT 425",
    type: "大學解剖實驗教材",
    url: "https://genent.cals.ncsu.edu/students/lab-schedule/lab-6-insect-internal-anatomy/",
    scope: "蟑螂背側解剖與器官辨識。",
  },
  digestion: {
    title:
      "Physiology of digestion and the molecular characterization of the major digestive enzymes from Periplaneta americana",
    author: "Tamaki et al. · Journal of Insect Physiology · 2014",
    type: "同儕審查研究",
    url: "https://www.sciencedirect.com/science/article/pii/S0022191014001632",
    scope: "美洲蟑螂消化酵素、嗉囊、中腸與胃盲囊；研究使用成年雄蟲。",
  },
  gut: {
    title: "Digestive and Excretory Systems",
    author: "NC State University · ENT 425",
    type: "大學教學資料",
    url: "https://genent.cals.ncsu.edu/bug-bytes/digestive-system/",
    scope: "昆蟲前、中、後腸及水鹽回收的一般原理。",
  },
  gizzard: {
    title:
      "Serotonergic transmission and gap junctional coupling in proventricular muscle cells in the American cockroach",
    author: "Journal of Insect Physiology · 2017",
    type: "同儕審查研究",
    url: "https://www.sciencedirect.com/science/article/abs/pii/S0022191016303122",
    scope: "前胃肌肉、幾丁質齒與神經調節。",
  },
  saliva: {
    title: "Function and operation of the cockroach salivary reservoir",
    author: "Journal of Insect Physiology · 1968",
    type: "同儕審查研究",
    url: "https://doi.org/10.1016/0022-1910(68)90130-3",
    scope: "唾液儲囊與分泌液的儲存、潤濕及消化作用。",
  },
  tubules: {
    title:
      "Morphology and function of Malpighian tubules and associated structures in the cockroach, Periplaneta americana",
    author: "Wall, Oschman & Schmidt · Journal of Morphology · 1975",
    type: "同儕審查研究",
    url: "https://pubmed.ncbi.nlm.nih.gov/1152069/",
    scope: "馬氏管分區及其與中、後腸交界的連接；每隻約 150 條。",
  },
  rectum: {
    title: "Water and solute uptake by rectal pads of Periplaneta americana",
    author: "PubMed · 1970",
    type: "同儕審查研究",
    url: "https://pubmed.ncbi.nlm.nih.gov/5435422/",
    scope: "直腸墊的水分與溶質吸收。此條僅核對書目與研究主題。",
  },
  air: {
    title: "Respiratory System",
    author: "NC State University · ENT 425",
    type: "大學教學資料",
    url: "https://genent.cals.ncsu.edu/bug-bytes/respiratory-system/",
    scope: "氣門、氣管、微氣管與氣體交換的一般原理。",
  },
  ventilation: {
    title:
      "Pacemaker for tracheal ventilation in the cockroach, Periplaneta americana",
    author: "Journal of Insect Physiology · 1967",
    type: "同儕審查研究",
    url: "https://doi.org/10.1016/0022-1910(67)90166-7",
    scope: "後胸神經節與腹部呼氣肌節律。",
  },
  blood: {
    title: "Circulatory System",
    author: "NC State University · ENT 425",
    type: "大學教學資料",
    url: "https://genent.cals.ncsu.edu/bug-bytes/circulatory-system/",
    scope: "開放式循環、背血管及血淋巴功能的一般原理。",
  },
  fat: {
    title:
      "Nitrogen recycling and nutritional provisioning by Blattabacterium, the cockroach endosymbiont",
    author: "Sabree, Kambhampati & Moran · PNAS · 2009",
    type: "同儕審查研究",
    url: "https://pubmed.ncbi.nlm.nih.gov/19880743/",
    scope: "美洲蟑螂共生菌基因體與氮再利用的代謝推論。",
  },
  fatcells: {
    title:
      "Cloning of PaAtg8 and roles of autophagy in adaptation to starvation with respect to the fat body and midgut",
    author: "Park & Takeda · Cell and Tissue Research · 2014",
    type: "同儕審查研究",
    url: "https://pubmed.ncbi.nlm.nih.gov/24696316/",
    scope: "脂肪體細胞種類、尿酸儲存與飢餓時的自噬。",
  },
  nerves: {
    title: "Neural Circuit Recording from an Intact Cockroach Nervous System",
    author: "Journal of Visualized Experiments · 2013",
    type: "同儕審查研究",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3969889/",
    scope: "腹神經索、尾鬚感覺毛、末端神經節與逃跑神經迴路。",
  },
  antenna: {
    title:
      "Cellular Organization of an Antennal Mechanosensory Pathway in the Cockroach, Periplaneta americana",
    author: "Journal of Neuroscience · 1996",
    type: "同儕審查研究",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6578969/",
    scope: "觸角機械感覺與下行神經路徑。",
  },
  eyes: {
    title:
      "Electrical interactions between photoreceptors in the compound eye of Periplaneta americana",
    author: "Saari et al. · Journal of Experimental Biology · 2018",
    type: "同儕審查研究",
    url: "https://pubmed.ncbi.nlm.nih.gov/30224371/",
    scope: "複眼中的紫外光及綠光敏感受器。",
  },
  ocelli: {
    title: "The role of ocelli in cockroach optomotor performance",
    author: "原始研究 · 2018",
    type: "同儕審查研究",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5799336/",
    scope: "美洲蟑螂額部的兩個單眼及視動反應。",
  },
  ovaries: {
    title:
      "Oocyte differentiation and vitellogenesis in the roach Periplaneta americana",
    author: "Anderson · Journal of Cell Biology · 1964",
    type: "同儕審查研究",
    url: "https://pubmed.ncbi.nlm.nih.gov/14105205/",
    scope: "卵巢小管與不同發育階段的卵母細胞。",
  },
  female: {
    title:
      "The genital tract and spermatheca of Periplaneta americana: histochemical and ultrastructural study",
    author: "原始組織學研究 · 1966",
    type: "同儕審查研究",
    url: "https://pubmed.ncbi.nlm.nih.gov/6012142/",
    scope: "雌性生殖道及受精囊；此條僅核對書目與研究主題。",
  },
  femaleGeneral: {
    title: "Female Reproductive System",
    author: "NC State University · ENT 425",
    type: "大學教學資料",
    url: "https://genent.cals.ncsu.edu/bug-bytes/reproductive-system/females/",
    scope: "側輸卵管與共同輸卵管的連接，以及受精囊的精子儲存功能。",
  },
  glands: {
    title:
      "The role of JH III and ecdysterone in the regulation of the left colleterial gland activities in Periplaneta americana",
    author: "原始研究 · 1988",
    type: "同儕審查研究",
    url: "https://pubmed.ncbi.nlm.nih.gov/2457540/",
    scope: "附膠腺的分泌活動與卵鞘形成之協調。",
  },
  male: {
    title: "Male Reproductive System",
    author: "NC State University · ENT 425",
    type: "大學教學資料",
    url: "https://genent.cals.ncsu.edu/bug-bytes/reproductive-system/male-reproductive-system/",
    scope:
      "精巢、輸精管、附屬腺與射精管的一般昆蟲原理；模型不呈現物種特異的生殖器細節。",
  },
};

const part = (
  id,
  name,
  en,
  system,
  location,
  description,
  detail,
  note,
  refs,
  options = {},
) => ({
  id,
  name,
  en,
  system,
  location,
  description,
  detail,
  note,
  refs,
  ...options,
});

// IDs 01–16 follow the supplied book's key; 17–64 extend its scope.
export const organs = [
  part(
    1,
    "革質前翅",
    "Tegmina",
    "external",
    "中胸背側，覆在後翅上方",
    "硬化而有韌性的前翅覆蓋膜質後翅與腹部，形成外側保護。",
    "成蟲前翅呈帶光澤的紅褐色，質地較厚，稱為覆翅或革質前翅（tegmina）。細密翅脈延伸到翅端；休息時左翅覆在右翅上方。模型參考補充照片的栗紅色與較透光的翅端。",
    "書中以 wing case 稱呼；它仍是一對翅，與甲蟲高度硬化的鞘翅不同。",
    ["indoorAtlas", "uf", "external"],
    { depth: 0 },
  ),
  part(
    2,
    "膜質後翅",
    "Hindwings",
    "external",
    "後胸背側，收在前翅下方",
    "薄而寬的膜翅可以沿翅脈摺起，收納在身體背面。",
    "後翅的褶皺使大面積的翅膜能折成較小的體積。飛行能力受種類、性別與環境影響；這裡呈現美洲蟑螂成蟲的翅。",
    "模型把後翅展成扇面方便觀察，並非蟑螂休息時的實際姿態。",
    ["uf"],
    { depth: 1 },
  ),
  part(
    3,
    "外骨骼",
    "Exoskeleton",
    "external",
    "包覆全身的體壁",
    "支撐身體、保護器官，也為肌肉提供施力的附著點。",
    "外層表皮含幾丁質與蛋白質；硬化板片之間以較柔軟的膜相連。表面蠟質有助減少水分散失。生長中的若蟲需要蛻皮才能擴大體形。",
    "掀開的「背板」只是外骨骼的一部分；腹面、足與觸角同樣有外骨骼。",
    ["skeleton", "lab"],
    { depth: 2 },
  ),
  part(
    4,
    "氣管與微氣管",
    "Tracheal system",
    "respiratory",
    "從體側氣門分支到各組織",
    "一張把空氣送往組織的細管網，代替肺的功能。",
    "較大的氣管有螺旋狀的表皮加厚，維持管腔暢通；分支愈來愈細，末端微氣管使氧氣接近細胞。腹部運動也能協助換氣。",
    "藍綠色是辨識用的配色。實際分支極密，圖中只顯示代表性路徑。",
    ["air", "ventilation"],
  ),
  part(
    5,
    "背血管與心臟",
    "Dorsal vessel",
    "circulatory",
    "消化道上方、靠近背側體壁",
    "沿背部排列的管狀心臟，把血淋巴向前輸送。",
    "背血管的心臟區可經心門接收血淋巴，前方連接主動脈。血淋巴離開血管後流入體腔，接觸器官，再回到循環中。",
    "蟑螂不是靠血淋巴大量運送氧氣；氧氣主要經氣管系統抵達組織。",
    ["blood"],
  ),
  part(
    6,
    "脂肪體",
    "Fat body",
    "circulatory",
    "體腔內、器官周圍的片狀組織",
    "兼具營養儲存與代謝功能，並與共生菌一起參與氮的再利用。",
    "脂肪體含儲存養分的細胞、累積尿酸的細胞，以及容納 Blattabacterium 的菌細胞。基因體研究指出，共生菌可利用尿素與氨等產物合成胺基酸。",
    "不能把脂肪體理解成單純的油脂，也不能說共生菌直接完成全部尿酸分解。",
    ["fat", "fatcells"],
  ),
  part(
    7,
    "腹神經索",
    "Ventral nerve cord",
    "nervous",
    "消化道下方，沿身體腹側",
    "成對縱向神經連結各神經節，傳送感覺與動作訊號。",
    "尾鬚偵測到的氣流訊息會進入末端腹神經節，再經大型神經纖維影響運動迴路。這種分散的組織方式讓不同體節能參與反應。",
    "神經索在腹側，心臟在背側；兩者不是同一條構造。",
    ["nerves"],
  ),
  part(
    8,
    "胸腹神經節",
    "Segmental ganglia",
    "nervous",
    "腹神經索上的膨大區",
    "各區域的神經處理中心，整合附近感覺與運動訊號。",
    "胸神經節與足部活動相關；腹部神經節參與局部反射與內臟調節。實驗也顯示後胸神經節與通氣節律有關。",
    "展示三個胸神經節與六個腹神經節的宏觀排列；未重建其中每一條神經纖維。",
    ["nerves", "ventilation"],
  ),
  part(
    9,
    "唾液腺與儲囊",
    "Salivary glands",
    "digestive",
    "前部胸腔，嗉囊兩旁",
    "分泌唾液，幫助潤濕食物並開始消化。",
    "腺體以導管連到口器附近，儲囊可暫存分泌液。美洲蟑螂唾液與中腸都有消化酵素，唾液澱粉酶與中腸澱粉酶並不相同。",
    "腺體是分泌部位；旁邊較平滑的囊狀部分負責儲存。",
    ["saliva", "digestion"],
  ),
  part(
    10,
    "食道",
    "Oesophagus",
    "digestive",
    "口與嗉囊之間",
    "把吞入的食物送往嗉囊的狹長通道。",
    "食道屬於前腸，向後與可膨大的嗉囊相連。它是食物流動的路徑，不是氣管，也不是心臟前端的主動脈。",
    "沿著橘色管道，由頭部一路追到腹部，就能看出消化道的連續性。",
    ["gut"],
  ),
  part(
    11,
    "嗉囊",
    "Crop",
    "digestive",
    "食道後方、前部體腔",
    "可伸展的食物暫存袋，讓取食與後續處理不必同步。",
    "嗉囊是美洲蟑螂前腸特別發達的部分。食物可在這裡停留並接觸消化液，之後送入前胃。不同取食狀態下，它的大小會明顯改變。",
    "它並不等同於人類胃；昆蟲各段消化道有自己的分工。",
    ["digestion"],
  ),
  part(
    12,
    "中腸",
    "Midgut",
    "digestive",
    "前胃之後，通向後腸",
    "消化酵素作用及養分吸收的重要區域。",
    "中腸與前端的胃盲囊共同參與消化與分泌。美洲蟑螂的研究顯示，多數消化作用集中在前腸與前段中腸，蛋白質末端消化也延續到後方。",
    "圖中彎曲的腸管經過整理與放大，實際盤繞會隨個體而改變。",
    ["digestion", "gut"],
  ),
  part(
    13,
    "馬氏管",
    "Malpighian tubules",
    "digestive",
    "中腸與後腸交界，游離於體腔",
    "細長的排泄小管，參與體液、水分與離子的調節。",
    "小管與血淋巴接觸，管內液體匯入腸道。顯微研究在美洲蟑螂記錄約 150 條，並指出小管本身有不同構造區段。",
    "模型僅畫少數代表管，並非真實數量；它們不是腎臟或腸道絨毛。",
    ["tubules"],
  ),
  part(
    14,
    "直腸與直腸墊",
    "Rectum & rectal pads",
    "digestive",
    "後腸末端、肛門之前",
    "在糞便排出前回收水分與溶質。",
    "直腸壁上的直腸墊參與吸收，使身體保留可再利用的水與鹽。它與馬氏管配合，維持內部環境。",
    "排便與排泄的產物都可經腸道末端離開，但其來源與處理過程不同。",
    ["rectum", "gut"],
  ),
  part(
    15,
    "卵巢",
    "Ovaries",
    "reproductive",
    "雌性腹部兩側",
    "成對卵巢由卵巢小管構成，內含不同成熟階段的卵母細胞。",
    "美洲蟑螂的卵巢小管為無滋養細胞型（panoistic）。卵母細胞沿小管排列，成熟過程中累積卵黃，為胚胎發育儲備養分。",
    "每側呈現八條卵巢管。淡色卵母細胞的大小表示發育序列，實際大小隨生殖週期而異。",
    ["ovaries"],
    { sex: "female" },
  ),
  part(
    16,
    "輸卵管",
    "Oviducts",
    "reproductive",
    "卵巢後方、腹部後段",
    "把成熟的卵從兩側卵巢送往共同生殖道。",
    "左右側輸卵管向後匯合，使卵進入產卵路徑。圖中的管道位置依解剖概念排列，與鄰近的消化道分開。",
    "輸卵管是運送通道，卵鞘則是卵排出時形成的保護構造。",
    ["femaleGeneral", "female"],
    { sex: "female" },
  ),
  part(
    17,
    "觸角",
    "Antennae",
    "nervous",
    "頭部前方的一對長附肢",
    "伸向環境的感覺探針，協助探索接觸物。",
    "觸角表面的感覺構造能提供環境線索。美洲蟑螂受到觸角機械刺激時，可經頭部的下行神經路徑引發反應；這與尾鬚氣流路徑不同。",
    "觸角呈細長絲狀，可超過體長。觸角採向前外側伸展的非對稱姿態，分節密度為渲染近似。",
    ["indoorAtlas", "antenna", "external"],
  ),
  part(
    18,
    "複眼",
    "Compound eyes",
    "nervous",
    "頭部左右兩側",
    "黑色、外形近腎形，由許多小眼構成的視覺器官。",
    "美洲蟑螂的複眼含對紫外光與綠光敏感的感光細胞。研究以細胞內電位記錄探討不同感受器間的電性互動。",
    "複眼不是數千個各自形成完整影像的小相機；此模型只用網面表示小眼排列。",
    ["indoorAtlas", "eyes"],
  ),
  part(
    19,
    "單眼",
    "Ocelli",
    "nervous",
    "額部，靠近觸角基部",
    "兩個較簡單的感光構造，提供環境光訊息。",
    "遮蔽美洲蟑螂單眼的實驗發現，單眼訊息會影響由複眼引導的視動表現。它們與複眼一起參與光環境的感受。",
    "圖中兩個淡色小點就是單眼，位置與比例經過放大。",
    ["ocelli"],
  ),
  part(
    20,
    "大顎",
    "Mandibles",
    "external",
    "頭部腹面、口部兩側",
    "成對咀嚼構造，用來切碎與處理食物。",
    "大顎在頭部肌肉帶動下運動。蟑螂的口器屬咀嚼式，搭配其他口器構造，把食物送入口中。",
    "背側觀察時口器不容易看清，模型將它們向前攤開。",
    ["lab", "skeleton"],
  ),
  part(
    21,
    "小顎、下唇與鬚",
    "Maxillae & labium",
    "external",
    "大顎周圍與後方",
    "協助操持食物，鬚狀構造提供近距離感覺。",
    "口器是多個附肢共同運作的組合。小顎與下唇協助定位食物，並與大顎的咀嚼動作配合。",
    "此處將多個相鄰構造合併標註；模型不呈現每一片口器骨片。",
    ["lab"],
  ),
  part(
    22,
    "前胸背板",
    "Pronotum",
    "external",
    "頭部後方，前胸背側",
    "盾狀背板從上方遮住部分頭部。",
    "扁平的前胸背板周緣有淡黃至黃橙色斑紋，中央紅褐色深色區常近 T 形，邊界並不銳利。它屬於胸部外骨骼；從背面看，頭的大部分被它遮蔽。",
    "補充照片可見斑紋隨個體改變，也有中央紅色區較大的個體。模型只示範一種外觀，不能只憑一個固定斑形判定物種。",
    ["indoorAtlas", "uf", "external"],
  ),
  part(
    23,
    "足與跗節",
    "Legs & tarsi",
    "external",
    "前胸、中胸、後胸各一對",
    "三對分節的足支撐身體，幫助快速行走。",
    "足由基部向末端分節，股節與脛節較醒目，末端跗節與爪接觸表面。肌肉牽動關節，讓足能改變方向與姿勢。",
    "足的顏色介於黃橙與紅褐之間，脛節上的棘刺很醒目。模型以尖端收細的棘刺表達外形，足部姿態為展示需要而攤平。",
    ["indoorAtlas", "lab", "skeleton"],
  ),
  part(
    24,
    "尾鬚",
    "Cerci",
    "nervous",
    "腹部末端左右兩側",
    "有感覺毛的成對附肢，能察覺細微氣流。",
    "氣流使尾鬚感覺毛偏轉，感覺神經將訊息送入末端腹神經節，參與快速逃跑反應。不同方向的刺激會形成不同神經訊號。",
    "補充圖鑑稱這對附肢為「尾毛」，本站統一標為尾鬚。雌雄都有尾鬚；雄性另有較小腹刺，是不同的構造。",
    ["indoorAtlas", "nerves", "ufsex"],
  ),
  part(
    25,
    "氣門",
    "Spiracles",
    "respiratory",
    "胸、腹部體側",
    "氣管系統與外界相通的入口，可調節開閉。",
    "氣門的閥門受小肌肉控制，協調氣體交換與水分保存。空氣通過氣門後，進入縱向氣管與逐級分支。",
    "氣門位在身體兩側，不在嘴巴；圖中只標出代表性的入口。",
    ["air"],
  ),
  part(
    26,
    "前胃（砂囊）",
    "Proventriculus",
    "digestive",
    "嗉囊與中腸之間",
    "具強壯肌肉與內部硬齒，進一步處理食物。",
    "美洲蟑螂前胃有發達環狀肌及六個幾丁質齒，能將固體食物磨碎後送往中腸。研究也探討其肌肉的神經傳遞。",
    "嗉囊與前胃是相鄰但不同的區段，不應合併成同一個袋狀器官。",
    ["gizzard"],
  ),
  part(
    27,
    "胃盲囊",
    "Gastric caeca",
    "digestive",
    "中腸前端周圍",
    "由腸道伸出的盲端囊，參與分泌與吸收。",
    "美洲蟑螂的研究在胃盲囊定位到澱粉酶與胰蛋白酶的分泌。這些囊狀延伸增加與腸內容物接觸的組織面積。",
    "胃盲囊連接中腸前端；較細且插入中、後腸交界的絲狀構造是馬氏管。",
    ["digestion"],
  ),
  part(
    28,
    "迴腸與結腸",
    "Ileum & colon",
    "digestive",
    "中腸之後、直腸之前",
    "把腸內容物送往直腸，也參與後腸的水鹽調節。",
    "前腸與後腸內面有表皮襯層；中腸的構造不同。後腸從中腸交界向後延伸，與馬氏管的開口相鄰。",
    "這條彎曲管道與生殖管道互不連通。",
    ["gut", "tubules"],
  ),
  part(
    29,
    "腦與頭部神經節",
    "Brain & head ganglia",
    "nervous",
    "頭部內，連接感官與腹神經索",
    "整合頭部感覺訊息，並與身體各神經節交換訊號。",
    "觸角接觸的訊息可透過頭部下行神經元傳至胸部運動中心。蟑螂的神經控制分布於腦與其他神經節，並非全部集中在頭部。",
    "為了看清位置，選擇神經系統時頭部外殼會淡化。",
    ["antenna", "nerves"],
  ),
  part(
    30,
    "血淋巴與體腔",
    "Hemolymph & hemocoel",
    "circulatory",
    "體腔，包圍各器官",
    "在開放式循環中運送養分、離子、荷爾蒙與代謝產物。",
    "血淋巴離開背血管後直接接觸組織。它也參與免疫防禦與體內壓力調節；昆蟲的氧氣輸送主要由另一套氣管系統負責。",
    "半透明色面用來表示流體空間，它不是包住內臟的一個囊。",
    ["blood"],
  ),
  part(
    31,
    "胸部肌肉",
    "Thoracic muscles",
    "external",
    "胸部外骨骼內側",
    "收縮時牽動骨骼與附肢，產生運動。",
    "昆蟲肌肉附著於外骨骼內側，透過關節把收縮轉成足與翅的運動。模型以成束紋理表達胸腔中的肌肉。",
    "此處展示代表性肌束，沒有逐條重建肌肉的起止點。",
    ["skeleton", "lab"],
  ),
  part(
    32,
    "受精囊",
    "Spermatheca",
    "reproductive",
    "雌性腹部後段，連接生殖道",
    "與交配後精子儲存相關的囊狀構造。",
    "受精囊與輸卵管及附膠腺各有不同功能；這裡依雌性生殖道的解剖概念標出相對位置。",
    "此構造尺寸小，模型特別放大；詳細微細結構可由所列原始研究追查。",
    ["femaleGeneral", "female"],
    { sex: "female" },
  ),
  part(
    33,
    "附膠腺",
    "Colleterial glands",
    "reproductive",
    "雌性腹部後方，生殖道附近",
    "分泌與卵鞘形成有關的物質。",
    "美洲蟑螂左附膠腺的研究顯示，分泌活動受生殖週期與荷爾蒙影響，並與排卵、卵鞘形成協調。",
    "卵鞘是在卵外形成的保護構造，不是卵巢本身。",
    ["glands"],
    { sex: "female" },
  ),
  part(
    34,
    "精巢",
    "Testes",
    "reproductive",
    "雄性腹部內，成對排列",
    "精子產生與發育的部位。",
    "精巢包含生殖濾泡。形成的精子進入管道並前往儲存及排出路徑；精巢與雌性卵巢在本圖中互相切換。",
    "雄性面板以一般昆蟲生殖原理介紹；外形、濾泡數與大小是簡化示意。",
    ["male", "lab"],
    { sex: "male" },
  ),
  part(
    35,
    "輸精管與儲精區",
    "Vasa deferentia",
    "reproductive",
    "精巢後方，通向射精管",
    "輸送精子，連接精巢與後續生殖道。",
    "精子沿管道移動，部分擴大區域可供儲存。兩側路徑最終與共同排出通道相連。",
    "使用自然淡色的成對管路表示，不對管道實際長度做量測宣稱。",
    ["male"],
    { sex: "male" },
  ),
  part(
    36,
    "雄性附屬腺",
    "Male accessory glands",
    "reproductive",
    "雄性腹部後方、生殖道附近",
    "分泌支持精子與形成精包所需的物質。",
    "昆蟲雄性附屬腺的分泌物可構成精液成分，並參與包覆精子的精包形成。",
    "此處將附屬腺群合併顯示，不代表每一條分支或物種特異的形態。",
    ["male"],
    { sex: "male" },
  ),
  part(
    37,
    "射精管",
    "Ejaculatory duct",
    "reproductive",
    "雄性腹部後段的共同通道",
    "將精子及相關分泌物送往生殖開口。",
    "它是雄性生殖管道的末段，與後腸及肛門為不同路徑。圖中以淡色共同管道表示。",
    "本圖不對外生殖器的分類辨識構造進行細部建模。",
    ["male"],
    { sex: "male" },
  ),
  ...detailedParts,
];

export const organById = new Map(organs.map((o) => [o.id, o]));
export const systemById = new Map(systems.map((s) => [s.id, s]));
export const getOrgans = (system, sex = "female") =>
  organs.filter(
    (o) => (!system || o.system === system) && (!o.sex || o.sex === sex),
  );
export const requiredDepth = (o) =>
  o.depth ?? ([17, 18, 19, 20, 21, 22, 23, 24, 25].includes(o.id) ? 0 : 3);
