// Length ranges are source observations, not dimensions measured from these meshes.
export const speciesList = [
  {
    id: "american",
    name: "美洲蟑螂",
    formal: "美洲家蠊",
    latin: "Periplaneta americana",
    page: "index.html",
    number: "01",
    size: "32–45 mm",
    mm: 38,
    pattern: "american",
    width: { female: 1, male: 0.96 },
    wing: { female: 1, male: 1.03 },
    shell: "#773821",
    leg: "#854322",
    wingColors: ["#4c1b16", "#67251a", "#884724"],
    pronotumColors: ["#c39948", "#deb668", "#bd853d"],
    cerci: 1,
    ovarioles: 8,
    tagline: "紅褐色的長翅之下，藏著完整的器官世界。",
    diagnostic: "紅褐色體表、前胸背板淡黃色邊緣與中央深色斑，尾鬚細長。",
    sexNote: "雌雄皆具發達翅；雄性腹端另有一對腹刺。",
    habitat: "常見於溫暖、潮濕的環境與建築物周圍。",
    reproduction: "雌性將卵封入卵鞘；模型呈現卵巢、卵巢管及輸卵管。",
    refs: ["uf", "indoorAtlas"],
    featureParts: [22, 24, 59],
    evidence: "以美洲蟑螂文獻重建；仍非 CT 分割或可量測標本。",
  },
  {
    id: "german",
    name: "德國蟑螂",
    formal: "德國姬蠊",
    latin: "Blattella germanica",
    page: "german.html",
    number: "02",
    size: "10–15 mm",
    mm: 13,
    pattern: "german",
    width: { female: 0.91, male: 0.77 },
    wing: { female: 0.96, male: 0.91 },
    shell: "#9b743d",
    leg: "#ac8548",
    wingColors: ["#826137", "#ad8951", "#c4a471"],
    pronotumColors: ["#c2a472", "#d3b880", "#ae8b52"],
    cerci: 0.8,
    ovarioles: 20,
    tagline: "認出兩道縱紋，再走進只有指甲大的身體。",
    diagnostic: "前胸背板有兩道深色平行縱紋；成蟲體型小，整體黃褐至褐色。",
    sexNote: "雄性較狹長、腹端漸尖；雌性較寬，腹端較圓。翅長與體寬隨性別切換。",
    habitat: "與人類居住環境密切相關，水、食物與藏身縫隙影響族群建立。",
    reproduction: "雌性通常攜帶卵鞘直到接近孵化；每側卵巢約 20 條卵巢管。",
    refs: ["germanUF", "germanOvary", "germanGland", "germanAtlas"],
    featureParts: [22, 59, 66],
    evidence:
      "本種外形、卵巢管數與雄性背腺有直接文獻；其餘內部為比較解剖參考。",
  },
  {
    id: "brown",
    name: "棕色蟑螂",
    formal: "棕色家蠊",
    latin: "Validiblatta brunnea",
    synonym: "Periplaneta brunnea",
    page: "brown.html",
    number: "03",
    size: "33–38 mm",
    mm: 35,
    pattern: "brown",
    width: { female: 1.04, male: 1 },
    wing: { female: 1, male: 1.01 },
    shell: "#61281e",
    leg: "#8b4a28",
    wingColors: ["#421a17", "#65271e", "#926134"],
    pronotumColors: ["#906135", "#ad7a40", "#804326"],
    cerci: 0.58,
    ovarioles: null,
    tagline: "相似的褐色輪廓，差別藏在尾端與背板。",
    diagnostic:
      "深紅褐色翅面沒有基部黃縱紋；前胸背板黃褐斑較模糊，有時近似錨形，尾鬚短粗。",
    sexNote: "雌雄成蟲均有發達翅。腹端板形狀與尾鬚是需要近距離觀察的鑑別位置。",
    habitat: "偏好溫暖、潮濕環境，常在戶外活動，也能進入室內。",
    reproduction:
      "以卵鞘保護卵。現有頁面不把美洲蟑螂的卵巢管或馬氏管數量當成本種測量。",
    refs: [
      "brownUF",
      "brownTaxonomy",
      "brownCanada",
      "brownAntenna",
      "brownAtlas",
    ],
    featureParts: [24, 22, 17],
    evidence: "本種外形與觸角感覺研究可查；內臟拓撲暫以美洲蟑螂作比較參考。",
    taxonomyNote:
      "採 Blattodea Species File 的現行組合 Validiblatta brunnea；舊文獻常用 Periplaneta brunnea。這裡的棕色蟑螂並非黑胸大蠊 P. fuliginosa。",
  },
  {
    id: "brown-banded",
    name: "棕帶蟑螂",
    formal: "長鬚帶蠊",
    latin: "Supella longipalpa",
    page: "brown-banded.html",
    number: "04",
    size: "13–14.5 mm",
    mm: 14,
    pattern: "banded",
    width: { female: 1.1, male: 0.82 },
    wing: { female: 0.7, male: 1.02 },
    shell: "#704b2c",
    leg: "#b58a47",
    wingColors: ["#704729", "#936539", "#b28a51"],
    pronotumColors: ["#b1955f", "#cfb582", "#a17f4d"],
    cerci: 0.72,
    ovarioles: null,
    tagline: "由金黃到栗褐，雌雄的翅面各有自己的紋路。",
    diagnostic:
      "前胸背板中央紅褐、周緣淡；雄性黃褐翅基有紅褐橫帶及較淡的前後區域。雌性較深色；若蟲的兩條淡帶尤其醒目。",
    sexNote: "雌性較深色、腹部較寬，短翅不覆蓋整個腹部；雄性翅覆蓋腹部。",
    habitat:
      "常見於家具、櫥櫃、高處層架或畫框背後；與德國蟑螂的典型藏身位置不同。",
    reproduction:
      "雌性第 4、5 腹背板有與性費洛蒙釋放相關的腺體；可切換至專屬部位 65 觀察。",
    refs: [
      "bandedUF",
      "bandedTaiEOL",
      "bandedGland",
      "bandedPheromone",
      "bandedAtlas",
    ],
    featureParts: [1, 22, 65],
    evidence: "本種翅長、雌雄外形與背板腺位置有文獻；其他內臟為比較解剖參考。",
  },
  {
    id: "harlequin",
    name: "家屋蟑螂",
    formal: "家屋斑蠊",
    latin: "Neostylopyga rhombifolia",
    page: "harlequin.html",
    number: "05",
    size: "20–30 mm",
    mm: 25,
    pattern: "harlequin",
    width: { female: 1.13, male: 1.08 },
    wing: { female: 0, male: 0 },
    shell: "#30281f",
    leg: "#bd9b64",
    wingColors: ["#46331f", "#b69964", "#58412c"],
    pronotumColors: ["#c8b682", "#d8c595", "#b8a06b"],
    cerci: 0.82,
    ovarioles: null,
    reducedWings: true,
    tagline: "掀開斑駁的背板，探索一隻沒有後翅的蟑螂。",
    diagnostic:
      "黑褐底、淡黃斑；前胸背板前緣近 M 形，中央有對稱淡斑。腹背板以側緣斑為主，前翅縮小且無後翅。",
    sexNote: "成蟲雌雄皆無完整後翅。外露的分節腹背板是正常成蟲形態。",
    habitat:
      "本頁名稱對應臺灣名錄的家屋斑蠊，亦稱花斑蟑螂；不是所有住屋蟑螂的統稱。",
    reproduction:
      "現階段採蟑螂共有的卵鞘與生殖系統比較解剖；尚未取得本種完整內臟三維資料。",
    refs: [
      "harlequinTaiEOL",
      "harlequinGuide",
      "harlequinRevision",
      "harlequinAtlas",
    ],
    featureParts: [1, 48, 22],
    evidence:
      "體色、翅退化與體長依本種資料；腹內器官是明示來源的比較解剖模型。",
  },
  {
    id: "australian",
    name: "澳洲蟑螂",
    formal: "澳洲家蠊",
    latin: "Validiblatta australasiae",
    synonym: "Periplaneta australasiae",
    page: "australian.html",
    number: "06",
    size: "27–35 mm",
    mm: 32,
    pattern: "australian",
    width: { female: 1, male: 0.96 },
    wing: { female: 1, male: 1.01 },
    shell: "#54261c",
    leg: "#9b5028",
    wingColors: ["#361916", "#56291d", "#996132"],
    pronotumColors: ["#cf9c43", "#d9ac57", "#b58134"],
    cerci: 0.78,
    ovarioles: null,
    tagline: "循著翅基的一抹金黃，掀開深褐色的身體。",
    diagnostic:
      "深紅褐色體表，前胸背板暗底與淡黃邊紋對比鮮明；兩片前翅基部外側各有黃橙色縱紋。",
    sexNote:
      "雌雄成蟲皆有完整翅，背面外觀接近；雄性腹端具尾鬚與腹刺，雌性沒有腹刺。",
    habitat:
      "多在溫暖、潮濕的戶外隱蔽處活動，也可能進入建物與溫室，會取食植物。",
    reproduction:
      "卵封於卵鞘中，雌性在孵化前便將卵鞘留在隱蔽處。內部生殖器官採比較解剖，不將美洲蟑螂的卵巢管數當成本種測量。",
    refs: [
      "australianUF",
      "australianTaxonomy",
      "australianAtlas",
      "australianGallery",
    ],
    featureParts: [1, 22, 62],
    evidence:
      "翅基縱紋、背板斑紋及腹端雌雄差異有本種資料；內臟為明示來源的比較解剖重建。",
    taxonomyNote:
      "現行名稱依 Blattodea Species File 為 Validiblatta australasiae；圖鑑與較早研究使用 Periplaneta australasiae，兩者指同一物種。體長 27–35 mm 採使用者圖鑑節錄；UF/IFAS 報告約 32–35 mm，來源的樣本範圍不同。",
  },
];
export const speciesById = new Map(speciesList.map((s) => [s.id, s]));
export function speciesFromPath(path) {
  const file = path.split("/").pop() || "index.html";
  return speciesList.find((s) => s.page === file) || speciesList[0];
}
export function layersFor(s) {
  return s.reducedWings
    ? [
        { depth: 0, label: "完整外觀" },
        { depth: 1, label: "掀開退化前翅" },
        { depth: 3, label: "打開斑紋背板" },
      ]
    : ["完整外觀", "掀開前翅", "展開後翅", "打開外骨骼"].map(
        (label, depth) => ({ label, depth }),
      );
}
